/*!
\file i_edit.h
\brief Tracktion-free audio edit port.
*/

#pragma once

#include <optional>
#include <rock_hero/core/audio_asset.h>
#include <rock_hero/core/audio_clip.h>
#include <rock_hero/core/timeline.h>
#include <rock_hero/core/track.h>
#include <string>

namespace rock_hero::audio
{

/*!
\brief Project-owned facade over the concrete Tracktion edit model.

This interface represents audio edit-model mutation, not transport control. Implementations may
update their paired transport state while applying an edit, but callers must use ITransport for
playback, position, and listener behavior.

Concrete adapters may support fewer playback tracks than core::Session can model. The current
Tracktion-backed implementation is intentionally minimal and provisions only one backend track.
Unsupported track and clip provisioning attempts fail explicitly rather than pretending that
independent backend playback exists.
*/
class IEdit
{
public:
    /*! \brief Destroys the audio-edit interface. */
    virtual ~IEdit() = default;

    /*!
    \brief Provisions a backend track mapped to a framework-free Session track id.

    The supplied id is generated by Session before this call so backend state and Session state can
    share one durable project-owned identity. Implementations must retain enough mapping state to
    find the backend track later from this id without exposing backend-specific identity types.
    On success, implementations return the framework-free track spec that Session should attach to
    the allocated id. Provisioning may mutate backend adapter state.

    \param track_id Session-allocated track id to bind to the backend track.
    \param name User-visible track name to apply when the backend supports it.
    \return Accepted track spec when the backend track was provisioned and mapped; std::nullopt
    otherwise.
    */
    [[nodiscard]] virtual std::optional<core::TrackSpec> provisionTrack(
        core::TrackId track_id, const std::string& name) = 0;

    /*!
    \brief Provisions an audio clip from an asset and returns the backend-accepted spec.

    Implementations inspect the asset, build the default full-source clip at the requested timeline
    position, apply it to the playback backend, and return the accepted framework-free clip spec.
    Session attaches the supplied clip id only after this call succeeds, keeping backend acceptance
    spec separate from session-owned identity. Provisioning may mutate backend adapter state.

    \param track_id Track whose audio clip should be updated.
    \param audio_clip_id Session-allocated id to map to the backend clip.
    \param audio_asset Framework-free audio asset used as the clip source.
    \param position Requested start position on the session timeline.
    \return Accepted clip spec when the backend provisioned it; std::nullopt otherwise.
    \note The track id must already have been mapped through provisionTrack().
    */
    [[nodiscard]] virtual std::optional<core::AudioClipSpec> provisionAudioClip(
        core::TrackId track_id, core::AudioClipId audio_clip_id,
        const core::AudioAsset& audio_asset, core::TimePosition position) = 0;

    // TODO: Expand this surface with project-owned clip and track edit commands when the editor
    // gains real timeline authoring behavior instead of the current single-file workflow.

    // TODO: Add a separate project-owned undo/history boundary when editor requirements justify
    // it. Do not expose juce::UndoManager or Tracktion types through this public contract.

protected:
    /*! \brief Creates the audio-edit interface. */
    IEdit() = default;

    /*! \brief Copies the audio-edit interface. */
    IEdit(const IEdit&) = default;

    /*! \brief Moves the audio-edit interface. */
    IEdit(IEdit&&) = default;

    /*!
    \brief Assigns the audio-edit interface from another interface.
    \return Reference to this audio-edit interface.
    */
    IEdit& operator=(const IEdit&) = default;

    /*!
    \brief Move-assigns the audio-edit interface from another interface.
    \return Reference to this audio-edit interface.
    */
    IEdit& operator=(IEdit&&) = default;
};

} // namespace rock_hero::audio
