/*!
\file i_edit.h
\brief Tracktion-free audio edit port.
*/

#pragma once

#include <optional>
#include <rock_hero/core/audio_asset.h>
#include <rock_hero/core/track.h>
#include <rock_hero/core/track_audio.h>
#include <string>

namespace rock_hero::audio
{

/*!
\brief Project-owned facade over the concrete Tracktion edit model.

This interface represents audio edit-model mutation, not transport control. Implementations may
update their paired transport state while applying an edit, but callers must use ITransport for
playback, position, and listener behavior.

Concrete adapters may support fewer playback tracks than core::Session can model. The current
Tracktion-backed implementation is intentionally minimal and provisions only one backend track.
Unsupported track and audio provisioning attempts fail explicitly rather than pretending that
independent backend playback exists.
*/
class IEdit
{
public:
    /*! \brief Destroys the audio-edit interface. */
    virtual ~IEdit() = default;

    /*!
    \brief Provisions a backend track mapped to a framework-free Session track id.

    The supplied id is generated by Session before this call so backend state and Session state can
    share one durable project-owned identity. Implementations must retain enough mapping state to
    find the backend track later from this id without exposing backend-specific identity types.
    On success, implementations return the framework-free track spec that Session should attach to
    the allocated id. Provisioning may mutate backend adapter state.

    \param track_id Session-allocated track id to bind to the backend track.
    \param name User-visible track name to apply when the backend supports it.
    \return Accepted track spec when the backend track was provisioned and mapped; std::nullopt
    otherwise.
    */
    [[nodiscard]] virtual std::optional<core::TrackSpec> provisionTrack(
        core::TrackId track_id, const std::string& name) = 0;

    /*!
    \brief Provisions full-source track audio and returns the backend-accepted value.

    Implementations inspect the asset, apply it to the playback backend as the track's complete
    audio source, and return the accepted framework-free value. Provisioning may mutate backend
    adapter state.

    \param track_id Track whose audio should be updated.
    \param audio_asset Framework-free audio asset used as the track audio source.
    \return Accepted track audio when the backend provisioned it; std::nullopt otherwise.
    \note The track id must already have been mapped through provisionTrack().
    */
    [[nodiscard]] virtual std::optional<core::TrackAudio> provisionTrackAudio(
        core::TrackId track_id, const core::AudioAsset& audio_asset) = 0;

    // TODO: Expand this surface with project-owned track edit commands when the editor gains real
    // timeline authoring behavior instead of the current single-file workflow.

    // TODO: Add a separate project-owned undo/history boundary when editor requirements justify
    // it. Do not expose juce::UndoManager or Tracktion types through this public contract.

protected:
    /*! \brief Creates the audio-edit interface. */
    IEdit() = default;

    /*! \brief Copies the audio-edit interface. */
    IEdit(const IEdit&) = default;

    /*! \brief Moves the audio-edit interface. */
    IEdit(IEdit&&) = default;

    /*!
    \brief Assigns the audio-edit interface from another interface.
    \return Reference to this audio-edit interface.
    */
    IEdit& operator=(const IEdit&) = default;

    /*!
    \brief Move-assigns the audio-edit interface from another interface.
    \return Reference to this audio-edit interface.
    */
    IEdit& operator=(IEdit&&) = default;
};

} // namespace rock_hero::audio
